name: Set TRMNL Office Status

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Pick a status image"
        required: true
        type: choice
        options:
        - CONFERENCE.png
        - IN-OFFICE.png
        - IN-OFFICE-MEETING.png
        - OFFSITE-MEETING.png
        - OOO-CAMPING.png
        - OOO-VACATION.png
        - OUT-IN-FIELD-PHOTOG.png
        - QUICK-CONVO.png
        - RED-STATUS.png
        - STUDIO-OPEN-DOOR.png
        - STUDIO-RECORDING.png
        - WORK-FROM-HOME.png


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Send image URL to TRMNL
        env:
          TRMNL_WEBHOOK_URL: ${{ secrets.TRMNL_WEBHOOK_URL }}
          FILENAME: ${{ github.event.inputs.filename }}
        run: |
          IMAGE_URL="https://raw.githubusercontent.com/gky501/TRMNL-Office-Status/main/images/${FILENAME}"
          curl -sS "${TRMNL_WEBHOOK_URL}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"merge_variables\": {\"image_url\": \"${IMAGE_URL}\"}}"
