name: Set TRMNL Office Status

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Pick a status image"
        required: true
        type: choice
        options:
          # IN OFFICE
          - IN-OFFICE.png
          - IN-OFFICE-MEETING.png
          - OUT-IN-FIELD-PHOTOG.png
          - OFFSITE-MEETING.png
          - STUDIO-OPEN-DOOR.png
          - STUDIO-RECORDING.png
          - BUSY-BUT-AVAL.png
          - QUICK-CONVO.png
          - RED-STATUS.png

          # ALT WORK LOC.
          - CONFERENCE.png
          - WORK-FROM-HOME.png

          # RETURNING ON…
          - BACK-MONDAY.png
          - BACK-TUESDAY.png
          - BACK-WEDNESDAY.png
          - BACK-THURSDAY.png
          - BACK-FRIDAY.png

          # BE RIGHT BACK
          - BRB-0800.png
          - BRB-0900.png
          - BRB-1000.png
          - BRB-1100.png
          - BRB-1200.png
          - BRB-1300.png
          - BRB-1400.png
          - BRB-1500.png
          - BRB-1600.png
          - BRB-1700.png

          # OUT
          - OUT-4-DAY.png
          - OUT-4-WKND.png
          - OOO-CAMPING.png
          - OOO-VACATION.png

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Send image URL to TRMNL
        env:
          TRMNL_WEBHOOK_URL: ${{ secrets.TRMNL_WEBHOOK_URL }}
          FILENAME: ${{ github.event.inputs.filename }}
        run: |
          IMAGE_URL="https://raw.githubusercontent.com/gky501/TRMNL-Office-Status/main/images/${FILENAME}"
          curl -sS "${TRMNL_WEBHOOK_URL}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"merge_variables\": {\"image_url\": \"${IMAGE_URL}\"}}"
