name: Set TRMNL Office Status

on:
  workflow_dispatch:
    inputs:
      filename:
        description: "Pick a status image"
        required: true
        type: choice
        options:
          - Stats_IN-OFFICE.png
          - Stats_IN-OFFICE-ALL.png
          - Stats_WORK-FROM-HOME-ALL.png
          - Stats_OFFSITE-MEETING-ALL.png
          - Stats_CONFERENCE-ALL.png
          - Stats_QUICK-CONVO-ALL.png
          - Stats_OUT-IN-FIELD-ALL-PHOTOS.png
          - Stats_STUDIO-ALL-OPEN-DOOR.png
          - Stats_STUDIO-T-E-S-RECORDING.png
          - Stats_OOO-CAMPING-PS.png
          - Stats_OOO-VACATION-EO.png
          - Stats_RED-STATUS-EO.png


jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Send image URL to TRMNL
        env:
          TRMNL_WEBHOOK_URL: ${{ secrets.TRMNL_WEBHOOK_URL }}
          FILENAME: ${{ github.event.inputs.filename }}
        run: |
          IMAGE_URL="https://raw.githubusercontent.com/gky501/TRMNL-Office-Status/main/images/${FILENAME}"
          curl -sS "${TRMNL_WEBHOOK_URL}" \
            -H "Content-Type: application/json" \
            -X POST \
            -d "{\"merge_variables\": {\"image_url\": \"${IMAGE_URL}\"}}"
